version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
          - nautic-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - nautic-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: nautic-{{ checksum "package.json" }}
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - nautic-{{ checksum "package.json" }}
      - run: yarn test
  release:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - nautic-{{ checksum "package.json" }}
      - run: npx semantic-release
workflows:
  version: 2
  test_release:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
